binary:
    - 'binary/**'
jvm-jersey:
    - 'jvm-jersey/**'
php7: 
    - 'php7/**'  
dotnet:
    - 'dotnet/**'     
dotnet20:
    - 'dotnet20/**'     
dotnet8:
    - 'dotnet8/**'     
go:   
    - 'go/**'     
jvm:  
    - 'jvm/**'     
nodejs:
    - 'nodejs/**'
perl: 
    - 'perl/**'
python:
    - 'python/**'
python-fastapi:
    - 'python-fastapi/**'
ruby: 
    - 'ruby/**'
tensorflow-serving:
    - 'tensorflow-serving/**'
